Add some libraries

diff --git a/build_venv b/build_venv
--- a/build_venv
+++ b/build_venv
@@ -91,3 +91,6 @@ echo "done."
 echo -n "Running make sqlite... "
 make -j $CORES sqlite  >>../build_venv.log 2>&1 || fail "Failed to complete sqlite"
 echo "done."
+echo -n "Running make CGAL... "
+make -j $CORES CGAL >>../build_venv.log 2>&1 || fail "Failed to complete CGAL"
+echo "done."
