- Fixed location of build log

diff --git a/build b/build
--- a/build
+++ b/build
@@ -44,12 +44,12 @@ if [ ! -x root/bin/cmake ]; then
   cmake ../src -DCMAKE_INSTALL_PREFIX=$curdir/root >../build-1.log 2>&1 || fail "Failed to run cmake: stage 1"
   echo "done."
   echo -n "Running make openssl... "
-  make -j 8  openssl >>../build-1.log 2>&1 || fail "Failed to complete make openssl: stage 1"
+  make -j 8  openssl >>../../build-1.log 2>&1 || fail "Failed to complete make openssl: stage 1"
   pushd ../src/openssl >/dev/null && make install >>../build-1.log 2>&1 && popd >/dev/null
   echo "done."
   echo -n "Running make world stage 1... "
   make -j 8  >>../build-1.log 2>&1 || fail "Failed to complete make: stage 1"
-  pushd ../src/cmake >/dev/null && make install >>../build-1.log 2>&1 && popd >/dev/null
+  pushd ../src/cmake >/dev/null && make install >>../../build-1.log 2>&1 && popd >/dev/null
   echo "done."
   popd >/dev/null
   src/clean
