- First wait and see if make world is a problem with openssl

diff --git a/build b/build
--- a/build
+++ b/build
@@ -38,7 +38,7 @@ if [ ! -x bin/cmake ]; then
   cmake ../src -DCMAKE_INSTALL_PREFIX=$curdir || fail "Failed to run cmake: stage 1"
   make -j 8 openssl || fail "Failed to complete make up to openssl: stage 1"
   make -j 8 cmake || fail "Failed to complete make up to cmake: stage 1"
-  make -j 8 || fail "Failed to complete make up to cmake: stage 1"
+  make -j 8 || fail "Failed to complete make world: stage 1"
   popd
   src/clean
   rm -rf .build
@@ -48,8 +48,6 @@ fi
 pushd .build 
 cmake ../src -DCMAKE_INSTALL_PREFIX=$curdir || fail "Failed to run cmake: stage 2"
 # ... and go again with full build
-make -j 8 openssl || fail "Failed to complete make up to openssl: stage 2"
-make -j 8 cmake || fail "Failed to complete make up to cmake: stage 2"
-make -j 8 || fail "Failed to complete make world: stage 2"
+make -j 8 || fail "Failed to complete make world"
 popd
 echo "Done!"
