Split python modules and install in venv

diff --git a/build_venv b/build_venv
--- a/build_venv
+++ b/build_venv
@@ -75,23 +75,29 @@ pushd .build_venv >/dev/null
 echo -n "Running cmake stage 1... "
 cmake ../src -DCMAKE_INSTALL_PREFIX="$DEVSTACK_TARGET" >../build_venv.log 2>&1 || fail "Failed to run cmake: stage 1"
 echo "done."
-echo -n "Running make openssl... "
-make -j $CORES  openssl >>../build_venv.log 2>&1 || fail "Failed to complete make openssl: stage 1"
-#pushd ../src/openssl >/dev/null && make install >>../../build_venv.log 2>&1 && popd >/dev/null
-echo "done."
-echo -n "Running make flex... "
-make -j $CORES flex >>../build_venv.log 2>&1 || fail "Failed to complete make: stage 1"
-echo "done."
-echo -n "Running make cmake... "
-make -j $CORES cmake  >>../build_venv.log 2>&1 || fail "Failed to complete make"
-pushd cmake-prefix/src/cmake-build >/dev/null && make install >>../../../../build_venv.log 2>&1 && popd >/dev/null
-echo "done."
-echo -n "Running make boost... "
-make -j $CORES boost  >>../build_venv.log 2>&1 || fail "Failed to complete boost"
-echo "done."
-echo -n "Running make sqlite... "
-make -j $CORES sqlite  >>../build_venv.log 2>&1 || fail "Failed to complete sqlite"
-echo "done."
-echo -n "Running make fftw... "
-make -j $CORES fftw cppunit >>../build_venv.log 2>&1 || fail "Failed to complete fftw"
-echo "done."
+if [ -z $1 ]; then
+  echo -n "Running make openssl... "
+  make -j $CORES  openssl >>../build_venv.log 2>&1 || fail "Failed to complete make openssl: stage 1"
+  #pushd ../src/openssl >/dev/null && make install >>../../build_venv.log 2>&1 && popd >/dev/null
+  echo "done."
+  echo -n "Running make flex... "
+  make -j $CORES flex >>../build_venv.log 2>&1 || fail "Failed to complete make: stage 1"
+  echo "done."
+  echo -n "Running make cmake... "
+  make -j $CORES cmake  >>../build_venv.log 2>&1 || fail "Failed to complete make"
+  pushd cmake-prefix/src/cmake-build >/dev/null && make install >>../../../../build_venv.log 2>&1 && popd >/dev/null
+  echo "done."
+  echo -n "Running make boost... "
+  make -j $CORES boost  >>../build_venv.log 2>&1 || fail "Failed to complete boost"
+  echo "done."
+  echo -n "Running make sqlite... "
+  make -j $CORES sqlite  >>../build_venv.log 2>&1 || fail "Failed to complete sqlite"
+  echo "done."
+  echo -n "Running make fftw... "
+  make -j $CORES fftw cppunit >>../build_venv.log 2>&1 || fail "Failed to complete fftw"
+  echo "done."
+else
+  echo -n "Running make $1... "
+  make -j $CORES $1 >>../build_venv.log 2>&1 || fail "Failed to complete $1"
+  echo "done."
+fi
