Remove fftwpp since it doesn't have an installer

diff --git a/build_venv b/build_venv
--- a/build_venv
+++ b/build_venv
@@ -92,6 +92,6 @@ echo "done."
 echo -n "Running make sqlite... "
 make -j $CORES sqlite  >>../build_venv.log 2>&1 || fail "Failed to complete sqlite"
 echo "done."
-echo -n "Running make fftw++... "
-make -j $CORES fftwpp >>../build_venv.log 2>&1 || fail "Failed to complete fftw++"
+echo -n "Running make fftw... "
+make -j $CORES fftw >>../build_venv.log 2>&1 || fail "Failed to complete fftw"
 echo "done."
