Fix build script to do what it says

diff --git a/build_venv b/build_venv
--- a/build_venv
+++ b/build_venv
@@ -92,5 +92,5 @@ echo -n "Running make sqlite... "
 make -j $CORES sqlite  >>../build_venv.log 2>&1 || fail "Failed to complete sqlite"
 echo "done."
 echo -n "Running make fftw++... "
-make -j $CORES >>../build_venv.log 2>&1 || fail "Failed to complete fftw++"
+make -j $CORES fftwpp >>../build_venv.log 2>&1 || fail "Failed to complete fftw++"
 echo "done."
