- Only explicitly remove source directory

diff --git a/src/download b/src/download
--- a/src/download
+++ b/src/download
@@ -16,21 +16,23 @@ function gnu_download()
   ext=$3
   stacked=$4
   file=$name-$version.$ext
+  if [ -d $name ]; then
+    return 0
+  fi
   if $stacked; then
     url=$GNU_MIRROR/$name/$name-$version/$file
   else
     url=$GNU_MIRROR/$name/$file
   fi
-  rm -rf $name
   mkdir -p .downloads
   if [ ! -f .downloads/$file ]; then
-    pushd .downloads && wget $url && popd || fail "Failed to get $name" || exit 1
+    pushd .downloads && wget $url && popd || fail "Failed to get $name"
   fi
   tar xf .downloads/$file && mv $name* $name
 } 
   
-gnu_download gmp 6.1.0 tar.xz || exit 1
-gnu_download mpfr 3.1.4 tar.xz || exit 1
-gnu_download mpc 1.0.3 tar.gz || exit 1
-gnu_download gcc 6.1.0 tar.gz true || exit 1
+gnu_download gmp 6.1.0 tar.x 
+gnu_download mpfr 3.1.4 tar.xz 
+gnu_download mpc 1.0.3 tar.gz 
+gnu_download gcc 6.1.0 tar.gz true
 
