Force checkout and submodule update

diff --git a/src/download b/src/download
--- a/src/download
+++ b/src/download
@@ -111,7 +111,8 @@ function git_download()
   branch=$3
   if [ -d $name ]; then
     pushd $name
-    git checkout $branch || fail "Failed to checkout $branch"
+    git checkout $branch --force || fail "Failed to checkout $branch"
+    git submodule update --init --recursive || fail "Failed to update submodules of $name"
     git pull --recurse-submodules || fail "Failed to pull $name"
     popd
   else
