- Updated pyside2 upstream location

diff --git a/src/download b/src/download
--- a/src/download
+++ b/src/download
@@ -174,6 +174,6 @@ if [ -d qt/qtwayland ]; then rm -rf qt/qtwayland; fi
 url_download qt-creator http://ftp2.nluug.nl/languages/qt/official_releases/qtcreator/4.0/4.0.2/qt-creator-opensource-src-4.0.2.tar.gz
 if [ -d qt-creator-opensource-src-4.0.2 ]; then mv qt-creator-opensource-src-4.0.2 qt-creator; fi
 
-if [ ! -d pyside2-setup ]; then
-  git clone --recursive https://github.com/PySide/pyside2-setup.git || fail "Failed to get PySide from git"
+if [ ! -d pyside-setup ]; then
+  git clone --recursive git://code.qt.io/pyside/pyside-setup.git || fail "Failed to get PySide from git"
 fi
