- Download wget asciidoc xmlto doxygen

diff --git a/src/download b/src/download
--- a/src/download
+++ b/src/download
@@ -156,11 +156,17 @@ gnm_download gtk+ 3.14 15
 gnm_download pygobject 3.20 1
 gnm_download glade 3.20 0
 
+gnu_download wget 1.18 tar.xz
+sf_download asciidoc 8.6.9 tar.gz
+url_download xmlto https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.28.tar.gz
 url_download git https://www.kernel.org/pub/software/scm/git/git-2.9.0.tar.xz
+url_download doxygen http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.src.tar.gz
 
 url_download qt http://ftp2.nluug.nl/languages/qt/archive/qt/5.7/5.7.0/single/qt-everywhere-opensource-src-5.7.0.tar.gz
 if [ -d qt-everywhere-opensource-src-5.7.0 ]; then mv qt-everywhere-opensource-src-5.7.0 qt; fi
 url_download qt-creator http://ftp2.nluug.nl/languages/qt/official_releases/qtcreator/4.0/4.0.2/qt-creator-opensource-src-4.0.2.tar.gz
 if [ -d qt-creator-opensource-src-4.0.2 ]; then mv qt-creator-opensource-src-4.0.2 qt-creator; fi
 
-git clone --recursive https://github.com/PySide/pyside2-setup.git
+if [ ! -d pyside2-setup ]; then
+  git clone --recursive https://github.com/PySide/pyside2-setup.git || fail "Failed to get PySide from git"
+fi
