- Added curl, cmake, bison, and flex

diff --git a/src/download b/src/download
--- a/src/download
+++ b/src/download
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 GNU_MIRROR=http://mirror.inode.at/gnu
+SF_HOST=http://prdownloads.sourceforge.net/
 
 function fail()
 {
@@ -28,7 +29,7 @@ function download()
   fi
   mkdir -p .downloads
   if [ ! -f .downloads/$file ]; then
-    pushd .downloads && wget $url && popd || fail "Failed to get $name"
+    pushd .downloads && wget --no-check-certificate $url && popd || fail "Failed to get $name"
   fi
   tar xf .downloads/$file && mv $name-* $name || mv "$name"_* $name || fail "Failed to unpack $name"
   patch_package $name
@@ -56,6 +57,16 @@ function gnu_download()
   fi
   download $name $file $url
 } 
+
+function sf_download()
+{
+  name=$1
+  version=$2
+  ext=$3
+  file=$name-$version.$ext
+  url=$SF_HOST/$name/$file
+  download $name $file $url
+}
   
 gnu_download gmp 6.1.0 tar.xz
 gnu_download mpfr 3.1.4 tar.xz 
@@ -74,8 +85,8 @@ url_download zlib http://zlib.net/zlib-1.2.8.tar.gz
 url_download bzip2 http://bzip.org/1.0.6/bzip2-1.0.6.tar.gz
 url_download libffi ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
 url_download pcre ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.tar.gz
-url_download expat http://prdownloads.sourceforge.net/expat/expat-2.1.1.tar.bz2
-url_download libpng http://prdownloads.sourceforge.net/libpng/libpng-1.6.22.tar.xz
+sf_download expat 2.1.1 tar.bz2
+sf_download libpng 1.6.22 tar.xz
 url_download icu http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz
 url_download json-c https://s3.amazonaws.com/json-c_releases/releases/json-c-0.12.1.tar.gz
 url_download OpenBLAS http://github.com/xianyi/OpenBLAS/archive/v0.2.18.tar.gz
@@ -89,3 +100,8 @@ url_download libxslt ftp://xmlsoft.org/libxml2/libxslt-1.1.29.tar.gz
 url_download openmpi https://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-1.10.2.tar.bz2
 url_download boost http://prdownloads.sourceforge.net/boost/boost_1_61_0.tar.bz2  
 if [ -d boost_1_61_0 ]; then mv boost_* boost; fi
+url_download libarchive http://libarchive.org/downloads/libarchive-3.2.0.tar.gz
+url_download curl https://curl.haxx.se/download/curl-7.49.1.tar.bz2
+url_download cmake https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz
+gnu_download bison 3.0.4 tar.xz
+sf_download flex 2.6.0 tar.xz
